set(OPENCC_FOUND TRUE)
set(OPENCC_LIBRARY "${PREBUILDER_LIB_DIR}/libopencc.a")
set(OPENCC_INCLUDE_DIR "${PREBUILDER_INCLUDE_DIR}/opencc")
add_library(OpenCC::OpenCC UNKNOWN IMPORTED)
set_target_properties(OpenCC::OpenCC PROPERTIES
    IMPORTED_LOCATION "${OPENCC_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${OPENCC_INCLUDE_DIR}"
)
