ASSUMPTION_OUTDATED = "Assumption outdated"
CHANGE_NOT_SAVED = "Change is not saved"
CHANGE_WRONGLY_SAVED = "Change should not be saved"
UI_NOT_UPDATED = "UI is not updated"
UI_WRONGLY_UPDATED = "UI should not be updated"
